[package]
name = "nannou_test"
version = "0.1.0"
edition = "2021"
authors = ["Stas Shtin 	<antisvin@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.18.1"
